version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'xyz'
  web:
    image: apiqcms/core
    command: rails s -p 3000 -b '0.0.0.0'
    environment:
      SECRET_TOKEN: abc
      RAILS_SERVE_STATIC_FILES: 'true'
      DATABASE: apiq
    volumes:
      - .:/kms
    ports:
      - "3000:3000"
    depends_on:
      - db
